package org.screamingsandals.bedwars.utils.flowergun.other.enums;

public enum ItemCategory {
    ITEM, CHESTPLATE, LEGGINS, BOOTS, HELMET, SWORD, AXE, BOW, CROSSBOW, ARROW_SIMPLE, ARROW_POTION, GADGET, POTION, WOODY, FIREWORK, WOOLY, BURNING, BLAZING, ENDERING, NETHERITE, STONE, GLASSY, SLIMY, ICY, LEATHERY, TOOLY, HEALING, SNOWBALL, DISABLED_LOOT, COLOURFUL, GILDED
}
